#!/bin/bash
#=============================================================
#  Tommy Tunnel v1.0.5
#  Author: hamb4
#  Iranian Server Client Script
#  GitHub: https://github.com/hamb4/tommy-tunnel
#
#  This script sets up port-forwarding tunnels on the Iranian
#  server. It works alongside 3x-ui's "External Proxy" feature.
#  No x-ray is needed inside the tunnel itself.
#
#  The Iranian server MUST receive the sync code generated by
#  the foreign server. All settings (method, port, key, etc.)
#  are decoded from the sync code and MUST match exactly.
#=============================================================

set -euo pipefail

VERSION="1.0.5"
AUTHOR="hamb4"
GITHUB_URL="https://github.com/hamb4/tommy-tunnel"

# ── Paths ──────────────────────────────────────────────────────
CONFIG_DIR="/etc/tommy"
TUNNEL_DIR="${CONFIG_DIR}/tunnels"
TUNNEL_LIST="${CONFIG_DIR}/tunnel_list"
CERT_DIR="${CONFIG_DIR}/certs"
SERVICE_PREFIX="tommy"

# ── Colours ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ── Helpers ────────────────────────────────────────────────────
msg()  { echo -e "${CYAN}[Tommy]${NC} $*"; }
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[X]${NC} $*"; }

separator() {
    echo -e "${DIM}─────────────────────────────────────────────────────${NC}"
}

# ── Banner ─────────────────────────────────────────────────────
print_banner() {
    clear
    echo -e "${PURPLE}${BOLD}"
    cat << 'BANNER'
  ████████╗██████╗ ███╗   ███╗██╗███╗   ██╗████████╗
  ╚══██╔══╝██╔══██╗████╗ ████║██║████╗  ██║╚══██╔══╝
     ██║   ██████╔╝██╔████╔██║██║██╔██╗ ██║   ██║   
     ██║   ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║   ██║   
     ██║   ██║  ██║██║ ╚═╝ ██║██║██║ ╚████║   ██║   
     ╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝   ╚═╝   
BANNER
    echo -e "${NC}"
    echo -e "  ${BOLD}Tommy Tunnel${NC} ${CYAN}v${VERSION}${NC}  ${DIM}|${NC}  Author: ${BOLD}${AUTHOR}${NC}"
    echo -e "  ${DIM}Iranian Server Client${NC}"
    echo -e "  ${DIM}${GITHUB_URL}${NC}"
    separator
    echo ""
}

# ── Config init ────────────────────────────────────────────────
init_config() {
    if [[ ! -d "${CONFIG_DIR}" ]]; then
        mkdir -p "${CONFIG_DIR}"
    fi
    if [[ ! -d "${TUNNEL_DIR}" ]]; then
        mkdir -p "${TUNNEL_DIR}"
    fi
    if [[ ! -d "${CERT_DIR}" ]]; then
        mkdir -p "${CERT_DIR}"
    fi
    if [[ ! -f "${TUNNEL_LIST}" ]]; then
        touch "${TUNNEL_LIST}"
    fi
}

# ── Get public IP ──────────────────────────────────────────────
get_ip() {
    local ip=""
    ip=$(curl -s4 --connect-timeout 5 https://ifconfig.me 2>/dev/null) \
        || ip=$(curl -s4 --connect-timeout 5 https://ip.sb 2>/dev/null) \
        || ip=$(curl -s4 --connect-timeout 5 https://icanhazip.com 2>/dev/null) \
        || ip=$(curl -s4 --connect-timeout 5 https://api.ipify.org 2>/dev/null)
    echo "${ip}"
}

# ── Generate random key ───────────────────────────────────────
generate_key() {
    openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | head -c 32
}

# ── Parse sync code ───────────────────────────────────────────
# Returns decoded fields on stdout:
#   METHOD|FOREIGN_IP|TUNNEL_PORT|TARGET_PORT|SHARED_KEY|SPEED_LEVEL[|WS_PATH]
parse_sync_code() {
    local code="$1"

    # Strip the TOMMY1.0.5: prefix
    local b64_data
    b64_data=$(echo "${code}" | sed 's/^TOMMY[0-9.]*://')

    # Decode
    local decoded
    decoded=$(echo "${b64_data}" | base64 -d 2>/dev/null) || {
        err "Invalid sync code. Cannot decode."
        return 1
    }

    # Validate format: must have at least 6 pipe-separated fields
    local field_count
    field_count=$(echo "${decoded}" | awk -F'|' '{print NF}')
    if [[ "${field_count}" -lt 6 ]]; then
        err "Invalid sync code format. Expected 6+ fields, got ${field_count}."
        return 1
    fi

    echo "${decoded}"
}

# ── Install dependencies ──────────────────────────────────────
check_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        err "This script must be run as root."
        exit 1
    fi
}

install_gost() {
    if command -v gost &>/dev/null; then
        ok "GOST is already installed."
        return 0
    fi

    msg "Installing GOST v2.12.0 ..."
    local GOST_VER="2.12.0"
    local GOST_URL="https://github.com/ginuerzh/gost/releases/download/v${GOST_VER}/gost-linux-amd64-${GOST_VER}.gz"

    if curl -fsSL --connect-timeout 15 "${GOST_URL}" -o /tmp/gost.gz 2>/dev/null; then
        gunzip -f /tmp/gost.gz 2>/dev/null || true
        chmod +x /tmp/gost 2>/dev/null
        mv /tmp/gost /usr/local/bin/gost 2>/dev/null
        ok "GOST v${GOST_VER} installed."
    else
        err "Failed to download GOST from GitHub."
        msg "Trying alternative download ..."
        local ALT_URL="https://github.com/ginuerzh/gost/releases/download/v${GOST_VER}/gost_${GOST_VER}_linux_amd64.tar.gz"
        if curl -fsSL --connect-timeout 15 "${ALT_URL}" -o /tmp/gost.tar.gz 2>/dev/null; then
            tar xzf /tmp/gost.tar.gz -C /tmp/ 2>/dev/null || true
            chmod +x /tmp/gost 2>/dev/null
            mv /tmp/gost /usr/local/bin/gost 2>/dev/null
            rm -f /tmp/gost.tar.gz
            ok "GOST installed via alternative method."
        else
            err "Could not install GOST. Please install manually."
            return 1
        fi
    fi
}

install_chisel() {
    if command -v chisel &>/dev/null; then
        ok "Chisel is already installed."
        return 0
    fi

    msg "Installing Chisel v1.10.1 ..."
    local CHISEL_VER="1.10.1"
    local CHISEL_URL="https://github.com/jpillora/chisel/releases/download/v${CHISEL_VER}/chisel_${CHISEL_VER}_linux_amd64.gz"

    if curl -fsSL --connect-timeout 15 "${CHISEL_URL}" -o /tmp/chisel.gz 2>/dev/null; then
        gunzip -f /tmp/chisel.gz 2>/dev/null || true
        chmod +x /tmp/chisel 2>/dev/null
        mv /tmp/chisel /usr/local/bin/chisel 2>/dev/null
        ok "Chisel v${CHISEL_VER} installed."
    else
        err "Failed to install Chisel. Please install manually."
        return 1
    fi
}

install_method() {
    local method="$1"
    case "${method}" in
        gost|paqet)
            install_gost
            ;;
        chisel)
            install_chisel
            ;;
    esac
}

# ── System optimisation for Iran network ──────────────────────
optimize_system() {
    msg "Optimising system for national network conditions ..."

    # BBR congestion control
    local current_cc
    current_cc=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "")
    if [[ "${current_cc}" != "bbr" ]]; then
        if modprobe tcp_bbr 2>/dev/null; then
            echo "tcp_bbr" >> /etc/modules-load.d/tommy-bbr.conf 2>/dev/null || true
            echo "net.core.default_qdisc=fq" >> /etc/sysctl.d/99-tommy.conf 2>/dev/null || true
            echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.d/99-tommy.conf 2>/dev/null || true
            sysctl --system >/dev/null 2>&1 || true
            ok "BBR congestion control enabled."
        else
            warn "Could not enable BBR. Your kernel may not support it."
        fi
    else
        ok "BBR already enabled."
    fi

    # TCP buffer optimisation
    cat >> /etc/sysctl.d/99-tommy.conf 2>/dev/null << 'SYSCTL' || true
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_wmem=4096 65536 16777216
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_keepalive_time=60
net.ipv4.tcp_keepalive_intvl=10
net.ipv4.tcp_keepalive_probes=6
net.ipv4.tcp_max_syn_backlog=8192
net.core.somaxconn=8192
net.core.netdev_max_backlog=8192
SYSCTL

    # UDP buffer optimisation (for QUIC / Paqet)
    cat >> /etc/sysctl.d/99-tommy.conf 2>/dev/null << 'SYSCTL' || true
net.core.rmem_default=1048576
net.core.wmem_default=1048576
SYSCTL

    sysctl --system >/dev/null 2>&1 || true
    ok "TCP/UDP buffer and keepalive settings applied."

    # File descriptor limits
    if ! grep -q "tommy" /etc/security/limits.conf 2>/dev/null; then
        cat >> /etc/security/limits.conf 2>/dev/null << 'LIMITS' || true
# Tommy Tunnel - file descriptor limits
*               soft    nofile          655350
*               hard    nofile          655350
root            soft    nofile          655350
root            hard    nofile          655350
LIMITS
    fi
    ok "File descriptor limits increased."

    # Open firewall ports for configured tunnels
    open_firewall_all
}

open_firewall_all() {
    while IFS= read -r tname; do
        [[ -z "${tname}" ]] && continue
        local conf="${TUNNEL_DIR}/${tname}.conf"
        if [[ -f "${conf}" ]]; then
            local port
            port=$(grep "^TUNNEL_PORT=" "${conf}" | cut -d= -f2)
            if [[ -n "${port}" ]]; then
                open_firewall_port "${port}"
            fi
        fi
    done < "${TUNNEL_LIST}"
}

open_firewall_port() {
    local port="$1"
    # ufw
    if command -v ufw &>/dev/null; then
        ufw allow "${port}"/tcp &>/dev/null || true
        ufw allow "${port}"/udp &>/dev/null || true
    fi
    # firewalld
    if command -v firewall-cmd &>/dev/null; then
        firewall-cmd --permanent --add-port="${port}"/tcp &>/dev/null || true
        firewall-cmd --permanent --add-port="${port}"/udp &>/dev/null || true
        firewall-cmd --reload &>/dev/null || true
    fi
    # iptables
    if command -v iptables &>/dev/null; then
        iptables -C INPUT -p tcp --dport "${port}" -j ACCEPT &>/dev/null 2>&1 || \
            iptables -I INPUT -p tcp --dport "${port}" -j ACCEPT &>/dev/null || true
        iptables -C INPUT -p udp --dport "${port}" -j ACCEPT &>/dev/null 2>&1 || \
            iptables -I INPUT -p udp --dport "${port}" -j ACCEPT &>/dev/null || true
    fi
}

# ── Save tunnel config ────────────────────────────────────────
save_tunnel_config() {
    local name="$1"
    local method="$2"
    local tunnel_port="$3"
    local target_port="$4"
    local shared_key="$5"
    local speed_level="$6"
    local foreign_ip="$7"
    local ws_path="$8"
    local sync_code="$9"

    cat > "${TUNNEL_DIR}/${name}.conf" << CONFEOF
NAME=${name}
METHOD=${method}
TUNNEL_PORT=${tunnel_port}
TARGET_PORT=${target_port}
SHARED_KEY=${shared_key}
SPEED_LEVEL=${speed_level}
FOREIGN_IP=${foreign_ip}
WS_PATH=${ws_path}
SYNC_CODE=${sync_code}
CREATED=$(date '+%Y-%m-%d %H:%M:%S')
CONFEOF

    # Add to tunnel list (if not already there)
    if ! grep -q "^${name}$" "${TUNNEL_LIST}"; then
        echo "${name}" >> "${TUNNEL_LIST}"
    fi
}

# ── Build command for systemd service (Iranian side = client) ─
build_service_command() {
    local name="$1"
    local method="$2"
    local tunnel_port="$3"
    local target_port="$4"
    local shared_key="$5"
    local speed_level="$6"
    local foreign_ip="$7"
    local ws_path="$8"

    local cmd=""

    case "${method}" in
        gost)
            if [[ -n "${ws_path}" ]]; then
                # GOST with TLS + WebSocket client
                cmd="/usr/local/bin/gost -L \"tcp://:${tunnel_port}/127.0.0.1:${target_port}\" -F \"relay+ws+tls://${shared_key}@${foreign_ip}:${tunnel_port}?path=${ws_path}\""
            else
                cmd="/usr/local/bin/gost -L \"tcp://:${tunnel_port}/127.0.0.1:${target_port}\" -F \"relay+tls://${shared_key}@${foreign_ip}:${tunnel_port}\""
            fi
            ;;
        chisel)
            cmd="/usr/local/bin/chisel client --auth tommy:${shared_key} ${foreign_ip}:${tunnel_port} ${tunnel_port}:127.0.0.1:${target_port}"
            ;;
        paqet)
            cmd="/usr/local/bin/gost -L \"tcp://:${tunnel_port}/127.0.0.1:${target_port}\" -F \"relay+quic://${shared_key}@${foreign_ip}:${tunnel_port}\""
            ;;
    esac

    echo "${cmd}"
}

# ── Create systemd service ────────────────────────────────────
create_service() {
    local name="$1"
    local cmd="$2"

    cat > "/etc/systemd/system/${SERVICE_PREFIX}-${name}.service" << SVCEOF
[Unit]
Description=Tommy Tunnel - ${name} (Iran)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${cmd}
Restart=always
RestartSec=5
LimitNOFILE=655350
Environment=GOST_LOG_MAX_SIZE=10485760

[Install]
WantedBy=multi-user.target
SVCEOF

    systemctl daemon-reload
}

# ── Create tunnel (interactive, with sync code) ───────────────
create_tunnel() {
    echo -e "${BOLD}${BLUE}── Create New Tunnel ──${NC}"
    echo ""
    echo -e "  ${YELLOW}The Iranian server MUST use the same settings as the foreign server.${NC}"
    echo -e "  ${YELLOW}Enter the sync code generated by the foreign server.${NC}"
    echo ""

    # ── Sync code ──
    local sync_code=""
    local decoded=""
    while [[ -z "${sync_code}" ]]; do
        read -rp "Enter sync code from foreign server: " sync_code
        if [[ -z "${sync_code}" ]]; then
            err "Sync code cannot be empty."
            continue
        fi

        decoded=$(parse_sync_code "${sync_code}") || {
            err "Invalid sync code. Please check and try again."
            sync_code=""
            continue
        }
    done

    # Parse decoded fields
    local method foreign_ip tunnel_port target_port shared_key speed_level ws_path
    method=$(echo "${decoded}" | cut -d'|' -f1)
    foreign_ip=$(echo "${decoded}" | cut -d'|' -f2)
    tunnel_port=$(echo "${decoded}" | cut -d'|' -f3)
    target_port=$(echo "${decoded}" | cut -d'|' -f4)
    shared_key=$(echo "${decoded}" | cut -d'|' -f5)
    speed_level=$(echo "${decoded}" | cut -d'|' -f6)
    ws_path=""
    if [[ "${method}" == "gost" ]]; then
        ws_path=$(echo "${decoded}" | cut -d'|' -f7)
    fi

    # Show decoded settings
    echo ""
    separator
    echo -e "  ${BOLD}${GREEN}Sync code decoded successfully!${NC}"
    separator
    echo -e "  ${BOLD}Method:${NC}       ${method}"
    echo -e "  ${BOLD}Foreign IP:${NC}   ${foreign_ip}"
    echo -e "  ${BOLD}Tunnel Port:${NC}  ${tunnel_port}"
    echo -e "  ${BOLD}Target Port:${NC}  ${target_port}"
    echo -e "  ${BOLD}Shared Key:${NC}   ${shared_key}"
    echo -e "  ${BOLD}Speed Level:${NC}  ${speed_level}"
    if [[ "${method}" == "gost" && -n "${ws_path}" ]]; then
        echo -e "  ${BOLD}WS Path:${NC}      ${ws_path}"
    fi
    separator
    echo ""

    # Confirm settings
    local confirm=""
    read -rp "Are these settings correct? [y/n]: " confirm
    if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
        msg "Cancelled. Please get a new sync code from the foreign server."
        return 0
    fi

    # Install dependencies for the selected method
    install_method "${method}" || {
        err "Failed to install dependencies for ${method}. Aborting."
        return 1
    }

    # ── Tunnel name ──
    echo ""
    local name=""
    while [[ -z "${name}" ]]; do
        read -rp "Enter a name for this tunnel (e.g. tunnel1): " name
        name=$(echo "${name}" | tr -d '[:space:]')
        if [[ -z "${name}" ]]; then
            err "Tunnel name cannot be empty."
            continue
        fi
        if [[ -f "${TUNNEL_DIR}/${name}.conf" ]]; then
            err "A tunnel named '${name}' already exists. Choose another name."
            name=""
            continue
        fi
        if ! echo "${name}" | grep -qE '^[a-zA-Z0-9_-]+$'; then
            err "Tunnel name can only contain letters, numbers, dashes, and underscores."
            name=""
            continue
        fi
    done

    # ── Save config ──
    save_tunnel_config "${name}" "${method}" "${tunnel_port}" "${target_port}" \
        "${shared_key}" "${speed_level}" "${foreign_ip}" "${ws_path}" "${sync_code}"

    # ── Build service command ──
    local svc_cmd
    svc_cmd=$(build_service_command "${name}" "${method}" "${tunnel_port}" "${target_port}" \
        "${shared_key}" "${speed_level}" "${foreign_ip}" "${ws_path}")

    # ── Create systemd service ──
    create_service "${name}" "${svc_cmd}"

    # ── Open firewall ──
    open_firewall_port "${tunnel_port}"

    # ── Enable and start ──
    systemctl enable "${SERVICE_PREFIX}-${name}" &>/dev/null
    systemctl start "${SERVICE_PREFIX}-${name}" &>/dev/null

    # ── Verify ──
    sleep 2
    if systemctl is-active --quiet "${SERVICE_PREFIX}-${name}"; then
        ok "Tunnel '${name}' is ${GREEN}ACTIVE${NC} and running."
    else
        warn "Tunnel '${name}' service started but may have issues."
        msg "Check with: systemctl status ${SERVICE_PREFIX}-${name}"
        msg "Journal: journalctl -u ${SERVICE_PREFIX}-${name} -n 30 --no-pager"
    fi

    # ── Show summary ──
    echo ""
    separator
    echo -e "  ${BOLD}${GREEN}Tunnel Created Successfully!${NC}"
    separator
    echo -e "  ${BOLD}Name:${NC}         ${name}"
    echo -e "  ${BOLD}Method:${NC}       ${method}"
    echo -e "  ${BOLD}Foreign IP:${NC}   ${foreign_ip}"
    echo -e "  ${BOLD}Tunnel Port:${NC}  ${tunnel_port} ${DIM}(on this Iranian server)${NC}"
    echo -e "  ${BOLD}Target Port:${NC}  ${target_port} ${DIM}(xray on foreign server)${NC}"
    echo -e "  ${BOLD}Speed Level:${NC}  ${speed_level}"
    echo ""
    echo -e "  ${BOLD}3x-ui External Proxy Configuration:${NC}"
    echo -e "  ${CYAN}  In 3x-ui → Stream Settings → External Proxy:${NC}"
    echo -e "  ${CYAN}  Destination: ${BOLD}$(get_ip)${NC}"
    echo -e "  ${CYAN}  Port:        ${BOLD}${tunnel_port}${NC}"
    separator
}

# ── Delete tunnel ─────────────────────────────────────────────
delete_tunnel() {
    echo -e "${BOLD}${RED}── Delete Tunnel ──${NC}"
    echo ""

    if [[ ! -s "${TUNNEL_LIST}" ]]; then
        warn "No tunnels configured."
        return 0
    fi

    echo -e "${BOLD}Configured tunnels:${NC}"
    local idx=1
    local names=()
    while IFS= read -r tname; do
        [[ -z "${tname}" ]] && continue
        local method="?"
        local port="?"
        local status="inactive"
        if [[ -f "${TUNNEL_DIR}/${tname}.conf" ]]; then
            method=$(grep "^METHOD=" "${TUNNEL_DIR}/${tname}.conf" | cut -d= -f2)
            port=$(grep "^TUNNEL_PORT=" "${TUNNEL_DIR}/${tname}.conf" | cut -d= -f2)
        fi
        if systemctl is-active --quiet "${SERVICE_PREFIX}-${tname}" 2>/dev/null; then
            status="${GREEN}active${NC}"
        else
            status="${RED}inactive${NC}"
        fi
        echo -e "  ${GREEN}${idx})${NC} ${BOLD}${tname}${NC}  ${DIM}method=${method}  port=${port}  status=${status}${NC}"
        names+=("${tname}")
        idx=$((idx + 1))
    done < "${TUNNEL_LIST}"

    if [[ ${#names[@]} -eq 0 ]]; then
        warn "No tunnels configured."
        return 0
    fi

    echo ""
    local choice=""
    read -rp "Select tunnel to delete (number) [0 to cancel]: " choice
    if [[ "${choice}" == "0" || -z "${choice}" ]]; then
        msg "Cancelled."
        return 0
    fi

    if ! echo "${choice}" | grep -qE '^[0-9]+$' || \
       [[ "${choice}" -lt 1 || "${choice}" -gt ${#names[@]} ]]; then
        err "Invalid selection."
        return 1
    fi

    local del_name="${names[$((choice - 1))]}"
    echo ""
    warn "You are about to DELETE tunnel '${del_name}'."
    read -rp "Type '${del_name}' to confirm deletion: " confirm
    if [[ "${confirm}" != "${del_name}" ]]; then
        msg "Deletion cancelled."
        return 0
    fi

    # Stop and disable service
    if systemctl is-active --quiet "${SERVICE_PREFIX}-${del_name}" 2>/dev/null; then
        systemctl stop "${SERVICE_PREFIX}-${del_name}" 2>/dev/null || true
    fi
    systemctl disable "${SERVICE_PREFIX}-${del_name}" 2>/dev/null || true

    # Remove service file
    rm -f "/etc/systemd/system/${SERVICE_PREFIX}-${del_name}.service"
    systemctl daemon-reload

    # Remove config files
    rm -f "${TUNNEL_DIR}/${del_name}.conf"

    # Remove from tunnel list
    sed -i "/^${del_name}$/d" "${TUNNEL_LIST}"

    ok "Tunnel '${del_name}' has been deleted."
}

# ── Service manager ────────────────────────────────────────────
service_manager() {
    while true; do
        echo -e "${BOLD}${BLUE}── Service Manager ──${NC}"
        echo ""

        if [[ ! -s "${TUNNEL_LIST}" ]]; then
            warn "No tunnels configured."
            return 0
        fi

        # List services with status
        local idx=1
        local names=()
        while IFS= read -r tname; do
            [[ -z "${tname}" ]] && continue
            local method="?"
            local port="?"
            local foreign_ip="?"
            local status="inactive"
            if [[ -f "${TUNNEL_DIR}/${tname}.conf" ]]; then
                method=$(grep "^METHOD=" "${TUNNEL_DIR}/${tname}.conf" | cut -d= -f2)
                port=$(grep "^TUNNEL_PORT=" "${TUNNEL_DIR}/${tname}.conf" | cut -d= -f2)
                foreign_ip=$(grep "^FOREIGN_IP=" "${TUNNEL_DIR}/${tname}.conf" | cut -d= -f2)
            fi
            if systemctl is-active --quiet "${SERVICE_PREFIX}-${tname}" 2>/dev/null; then
                status="${GREEN}active${NC}"
            else
                status="${RED}inactive${NC}"
            fi
            echo -e "  ${GREEN}${idx})${NC} ${BOLD}${tname}${NC}  ${DIM}method=${method}  port=${port}  foreign=${foreign_ip}  [${status}]${NC}"
            names+=("${tname}")
            idx=$((idx + 1))
        done < "${TUNNEL_LIST}"

        if [[ ${#names[@]} -eq 0 ]]; then
            warn "No tunnels configured."
            return 0
        fi

        echo ""
        echo -e "  ${GREEN}s)${NC} Start a tunnel"
        echo -e "  ${GREEN}p)${NC} Stop a tunnel"
        echo -e "  ${GREEN}r)${NC} Restart a tunnel"
        echo -e "  ${GREEN}t)${NC} Status of a tunnel"
        echo -e "  ${GREEN}0)${NC} Back to main menu"
        echo ""

        local action=""
        read -rp "Choose action: " action
        case "${action}" in
            0) return 0 ;;
            s|p|r|t)
                local sel=""
                read -rp "Select tunnel (number): " sel
                if ! echo "${sel}" | grep -qE '^[0-9]+$' || \
                   [[ "${sel}" -lt 1 || "${sel}" -gt ${#names[@]} ]]; then
                    err "Invalid selection."
                    continue
                fi
                local sname="${names[$((sel - 1))]}"
                local sname_svc="${SERVICE_PREFIX}-${sname}"
                case "${action}" in
                    s)
                        systemctl start "${sname_svc}" 2>/dev/null && ok "Tunnel '${sname}' started." || err "Failed to start '${sname}'."
                        ;;
                    p)
                        systemctl stop "${sname_svc}" 2>/dev/null && ok "Tunnel '${sname}' stopped." || err "Failed to stop '${sname}'."
                        ;;
                    r)
                        systemctl restart "${sname_svc}" 2>/dev/null && ok "Tunnel '${sname}' restarted." || err "Failed to restart '${sname}'."
                        ;;
                    t)
                        systemctl status "${sname_svc}" --no-pager 2>/dev/null || true
                        ;;
                esac
                ;;
            *) err "Invalid action." ;;
        esac
        echo ""
        read -rp "$(echo -e "${DIM}Press Enter to continue...${NC}")"
    done
}

# ── Test tunnel connectivity ──────────────────────────────────
test_tunnel() {
    echo -e "${BOLD}${BLUE}── Test Tunnel Connectivity ──${NC}"
    echo ""

    if [[ ! -s "${TUNNEL_LIST}" ]]; then
        warn "No tunnels configured."
        return 0
    fi

    local idx=1
    local names=()
    while IFS= read -r tname; do
        [[ -z "${tname}" ]] && continue
        echo -e "  ${GREEN}${idx})${NC} ${tname}"
        names+=("${tname}")
        idx=$((idx + 1))
    done < "${TUNNEL_LIST}"

    echo ""
    local choice=""
    read -rp "Select tunnel to test (number): " choice
    if ! echo "${choice}" | grep -qE '^[0-9]+$' || \
       [[ "${choice}" -lt 1 || "${choice}" -gt ${#names[@]} ]]; then
        err "Invalid selection."
        return 1
    fi

    local sel_name="${names[$((choice - 1))]}"
    local conf_file="${TUNNEL_DIR}/${sel_name}.conf"

    if [[ ! -f "${conf_file}" ]]; then
        err "Config file not found."
        return 1
    fi

    local foreign_ip tunnel_port
    foreign_ip=$(grep "^FOREIGN_IP=" "${conf_file}" | cut -d= -f2)
    tunnel_port=$(grep "^TUNNEL_PORT=" "${conf_file}" | cut -d= -f2)

    msg "Testing connectivity to ${foreign_ip}:${tunnel_port} ..."

    # TCP connectivity test
    if timeout 5 bash -c "echo >/dev/tcp/${foreign_ip}/${tunnel_port}" 2>/dev/null; then
        ok "TCP connection to ${foreign_ip}:${tunnel_port} succeeded."
    else
        warn "TCP connection to ${foreign_ip}:${tunnel_port} failed."
        msg "This could mean:"
        msg "  - The foreign server tunnel is not running"
        msg "  - The port is blocked by a firewall"
        msg "  - The foreign IP is unreachable"
    fi

    # Check service status
    if systemctl is-active --quiet "${SERVICE_PREFIX}-${sel_name}" 2>/dev/null; then
        ok "Local tunnel service '${sel_name}' is active."
    else
        err "Local tunnel service '${sel_name}' is NOT active."
        msg "Try: systemctl start ${SERVICE_PREFIX}-${sel_name}"
    fi
}

# ── About ──────────────────────────────────────────────────────
show_about() {
    echo ""
    separator
    echo -e "  ${BOLD}Tommy Tunnel${NC} ${CYAN}v${VERSION}${NC}"
    echo -e "  Author: ${BOLD}${AUTHOR}${NC}"
    echo -e "  GitHub: ${GITHUB_URL}"
    echo ""
    echo -e "  ${DIM}Tommy creates port-forwarding tunnels between your${NC}"
    echo -e "  ${DIM}Iranian server and foreign server. It works alongside${NC}"
    echo -e "  ${DIM}3x-ui's 'External Proxy' feature — the tunnel only${NC}"
    echo -e "  ${DIM}forwards a port, no x-ray is needed inside the tunnel.${NC}"
    echo ""
    echo -e "  ${DIM}Methods:${NC}"
    echo -e "  ${DIM}  • GOST  (TLS+WebSocket) – DPI-resistant${NC}"
    echo -e "  ${DIM}  • Chisel (HTTP)         – simple & reliable${NC}"
    echo -e "  ${DIM}  • Paqet  (QUIC/UDP)     – fast, hard to block${NC}"
    echo ""
    echo -e "  ${DIM}The sync code from the foreign server must be entered${NC}"
    echo -e "  ${DIM}here to ensure settings match exactly.${NC}"
    separator
    echo ""
    read -rp "$(echo -e "${DIM}Press Enter to continue...${NC}")"
}

# ── Main menu ──────────────────────────────────────────────────
main_menu() {
    while true; do
        print_banner

        # Show active tunnels count
        local tunnel_count=0
        if [[ -f "${TUNNEL_LIST}" ]]; then
            tunnel_count=$(grep -c "." "${TUNNEL_LIST}" 2>/dev/null || echo 0)
        fi
        local active_count=0
        while IFS= read -r tname; do
            [[ -z "${tname}" ]] && continue
            if systemctl is-active --quiet "${SERVICE_PREFIX}-${tname}" 2>/dev/null; then
                active_count=$((active_count + 1))
            fi
        done < "${TUNNEL_LIST}" 2>/dev/null || true

        echo -e "  ${DIM}Tunnels: ${tunnel_count} configured, ${active_count} active${NC}"
        echo ""
        echo -e "  ${GREEN}1)${NC} Create New Tunnel ${DIM}(requires sync code)${NC}"
        echo -e "  ${GREEN}2)${NC} Delete Tunnel"
        echo -e "  ${GREEN}3)${NC} Service Manager"
        echo -e "  ${GREEN}4)${NC} Test Tunnel Connectivity"
        echo -e "  ${GREEN}5)${NC} System Optimization"
        echo -e "  ${GREEN}6)${NC} About"
        echo -e "  ${RED}0)${NC} Exit"
        echo ""

        local choice=""
        read -rp "Your choice: " choice

        case "${choice}" in
            1) create_tunnel ;;
            2) delete_tunnel ;;
            3) service_manager ;;
            4) test_tunnel ;;
            5) optimize_system ;;
            6) show_about ;;
            0)
                msg "Goodbye! Tunnel services will keep running in the background."
                exit 0
                ;;
            *) err "Invalid choice." ;;
        esac

        echo ""
        read -rp "$(echo -e "${DIM}Press Enter to continue...${NC}")"
    done
}

# ── Entry point ────────────────────────────────────────────────
check_root
init_config
main_menu
